GET http://localhost:3000/service
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYWUwYjMxLWEyY2MtNDQ3Yy1iNmQ0LWIyOTc5MTg4ZWIxOCIsImlhdCI6MTY5MjI5NjE3MCwiZXhwIjoxNjkyMjk3MzcwfQ.omTnYyfvOQ1rDxlySUZ3fC-B86gEM6uPhmBev6detKU
###

POST http://localhost:3000/cliente/signup
Content-Type: application/json 

// ENPOINT PARA CADASTRAR USUÁRIO
{
    "name": "benjamin",
    "email": "benjamin@teste.com",
    "password": "ben123"
}
###

POST http://localhost:3000/cliente/login
Content-Type: application/json 

// ENDPOINT PARA FAZER LOGIN DE USUÁRIO NO SISMETAM LAMA!

{
    "email": "benjamin@teste.com",
    "password": "ben123"
}

###

POST http://localhost:3000/service
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYWUwYjMxLWEyY2MtNDQ3Yy1iNmQ0LWIyOTc5MTg4ZWIxOCIsImlhdCI6MTY5MjI4NzYyMywiZXhwIjoxNjkyMjg4ODIzfQ.Mm_9zMK2_PREbQyuZzc9p_XzEOus4Tm5ydy_h4NqwK4

// ENPOINT PARA CADASTRAR O TIPO DE SERVIÇO

{
    "typeService": "corte simples",
    "valueService": 20,
    "amount": 3
}