GET http://localhost:3000/service
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjBjNjkyLTU1ODgtNGYxNy1iZWMyLTQ1ODgzNDJmMWZiOCIsImlhdCI6MTY5NTkzMTE4NiwiZXhwIjoxNjk1OTMyMzg2fQ.gAIuSVZu5edTcoC12KJcSuKrF0VBkqkRLgz_FOiQZeo
###

POST http://localhost:3000/cliente/signup
Content-Type: application/json 

// ENPOINT PARA CADASTRAR USUÁRIO
{
    "name": "vinicius",
    "email": "vinicius@gmail.com",
    "password": "vini123"
}
###

POST http://localhost:3000/cliente/login
Content-Type: application/json 

// ENDPOINT PARA FAZER LOGIN DE USUÁRIO NO SISMETAM LAMA!

{
    "email": "vinicius@gmail.com",
    "password": "vini123"
}

###

POST http://localhost:3000/service
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjBjNjkyLTU1ODgtNGYxNy1iZWMyLTQ1ODgzNDJmMWZiOCIsImlhdCI6MTY5NTkyODQ3NiwiZXhwIjoxNjk1OTI5Njc2fQ.-WPvpL-C2bt45h-k3Loej0br8uTPEVeJzqs1deXHpgU

// ENPOINT PARA CADASTRAR O TIPO DE SERVIÇO

{
    "typeService": "corte simples",
    "valueService": 20,
    "amount": 3
}

###

PUT http://localhost:3000/service/4cfb63e9-065d-47e2-9d65-8e4b3d6ac827
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYWUwYjMxLWEyY2MtNDQ3Yy1iNmQ0LWIyOTc5MTg4ZWIxOCIsImlhdCI6MTY5MjI4NzYyMywiZXhwIjoxNjkyMjg4ODIzfQ.Mm_9zMK2_PREbQyuZzc9p_XzEOus4Tm5ydy_h4NqwK4

// ENPOINT PARA ATUALIZAR O TIPO DE SERVIÇO

{
    "typeService": "corte completo",
    "valueService": 30,
    "amount": 2
}