
GET https://tender-neckerchief-mite.cyclic.app/cliente/perfil
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjBjNjkyLTU1ODgtNGYxNy1iZWMyLTQ1ODgzNDJmMWZiOCIsImlhdCI6MTY5NjUzOTIwNCwiZXhwIjoxNjk2NTQyODA0fQ.526qSEUQwuK8qezH1LK8M48b_VFsH3A_uAkEUXqVUXQ
###


GET http://localhost:3000/service
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjBjNjkyLTU1ODgtNGYxNy1iZWMyLTQ1ODgzNDJmMWZiOCIsImlhdCI6MTY5NjUzOTIwNCwiZXhwIjoxNjk2NTQyODA0fQ.526qSEUQwuK8qezH1LK8M48b_VFsH3A_uAkEUXqVUXQ
###


GET http://localhost:3000/service/mes
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjBjNjkyLTU1ODgtNGYxNy1iZWMyLTQ1ODgzNDJmMWZiOCIsImlhdCI6MTY5NjUzOTIwNCwiZXhwIjoxNjk2NTQyODA0fQ.526qSEUQwuK8qezH1LK8M48b_VFsH3A_uAkEUXqVUXQ
###

POST http://localhost:3000/cliente/signup
Content-Type: application/json 

// ENPOINT PARA CADASTRAR USUÁRIO
{
    "name": "vinicius",
    "email": "vinicius@gmail.com",
    "password": "vini123"
}
###

POST http://localhost:3000/cliente/login
Content-Type: application/json 

// ENDPOINT PARA FAZER LOGIN DE USUÁRIO NO SISMETAM LAMA!

{
    "email": "vinicius@gmail.com",
    "password": "vini123"
}

###

POST http://localhost:3000/service
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjBjNjkyLTU1ODgtNGYxNy1iZWMyLTQ1ODgzNDJmMWZiOCIsImlhdCI6MTY5NjE4NzE1NSwiZXhwIjoxNjk2MTkwNzU1fQ.oBGwSvtc67R926Re3K5lI1bWaVIYmlGJgBtOMv1LG4w

// ENPOINT PARA CADASTRAR O TIPO DE SERVIÇO

{
    "typeService": "corte completo",
    "valueService": 30,
    "amount":4
}

###

PUT http://localhost:3000/service/4cfb63e9-065d-47e2-9d65-8e4b3d6ac827
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMzYWUwYjMxLWEyY2MtNDQ3Yy1iNmQ0LWIyOTc5MTg4ZWIxOCIsImlhdCI6MTY5MjI4NzYyMywiZXhwIjoxNjkyMjg4ODIzfQ.Mm_9zMK2_PREbQyuZzc9p_XzEOus4Tm5ydy_h4NqwK4

// ENPOINT PARA ATUALIZAR O TIPO DE SERVIÇO

{
    "typeService": "corte completo",
    "valueService": 30,
    "amount": 2
}